print('--------------------------------')
print('Informe o tamanho do arquivo')
print('e a velocidade de conexão')
print('para calcular a velocidade')
print('de download deste arquivo.')
print('--------------------------------')
t = float(input('Tamanho do arquivo (MB):'))
v = float(input('Velocidade de conexão (Mbps):'))
print('--------------------------------')
tamanho = round((t * 8),2)
tempomin = (tamanho / v)/60
tempominint = int(tempomin)
temposec = int((tempomin - tempominint)*60)
print('Tempo de download: %dmin %dsec' %(tempominint, temposec))
print('--------------------------------')