print('---------------------------------------')
print('              Tinturas SA              ')
area = float(input('Informe a área em m² a ser pintada:'))
volume = float(area * 6)
lata18 = float(volume / 18)
lata18 = int(lata18 + (1 if lata18 > int(lata18) else 0))
preco18 = lata18 * 80
preco18 = round(preco18,2)
galao36 = float(volume / 3.6)
galao36 = int(galao36 + (1 if galao36 > int(galao36) else 0))
preco36 = galao36 * 25
preco36 = round(preco36,2)
print('---------------------------------------')
print('            Compra em Latas            ')
print('Para %dm², você precisará de %d' %(area, lata18))
print('lata(s) de tinta, o que custará RS%d.' %(preco18))
print('---------------------------------------')
print('            Compra em Galões           ')
print('Para %dm², você precisará de %d' %(area, galao36))
print('galão(ões) de tinta, o que custará R$%d.' %(preco36))
print('---------------------------------------')
print('            Compra Combinada           ')
volume2 = float(area * 6)
lata18 = float(volume2 / 18)
lata18 = int(lata18)
resto = round(float(volume2 - (lata18 * 18)),2)
galao36 = float(resto / 3.6)
galao36 = int(galao36 + (1 if galao36 > int(galao36) else 0))
preco2 = round(((80 * lata18) + (25 * galao36)),2)
print('Para %dm², você precisará de %d' %(area, lata18))
print('lata(s) e %d galão(ões) de tinta,'%(galao36))
print('o que custará R$%d' %(preco2))
print('---------------------------------------')
print('INFO: Uma lata de tinta contém 18L')
print('INFO: Preço: R$80.00')
print('INFO: Um galão de tinta contém 3,6L')
print('INFO: Preço: R$25.00')
print('INFO: 3m² de cobertura requerem')
print('INFO: 1L de tinta.')
print('---------------------------------------')
